format = """$directory $git_branch$git_commit$git_status$git_state
$character"""

[character]
success_symbol = " ğŸ¦–[â¯](bold green)"
error_symbol   = " ğŸ’¥[â¯](bold red)"

[directory]
format = '[\[](purple)[$path]($style)[$read_only]($read_only_style)[\]](purple)'
read_only = " ï ½"
